const $ = (id) => document.getElementById(id);
const input = $("fileInput"), zone = $("dropZone"), preview = $("preview"), previewWrap = $("previewWrap");
let file, result;
function setStatus(value, state="") { const s=$("status"); s.textContent=value; s.className="status "+state; }
function choose(next) { file=next; if(!file) return; $("fileState").textContent=file.name; $("recognize").disabled=false; zone.hidden=true; previewWrap.hidden=false; const isPdf=file.type==="application/pdf"; $("pdfPreview").style.display=isPdf?"block":"none"; preview.style.display=isPdf?"none":"inline"; const url=URL.createObjectURL(file); if(isPdf) $("pdfPreview").src=url; else preview.src=url; setStatus("Ready"); }
input.onchange=()=>choose(input.files[0]); $("choose").onclick=()=>input.click(); $("replace").onclick=()=>input.click();
["dragenter","dragover"].forEach(e=>zone.addEventListener(e,x=>{x.preventDefault();zone.classList.add("drag")})); ["dragleave","drop"].forEach(e=>zone.addEventListener(e,x=>{x.preventDefault();zone.classList.remove("drag")})); zone.addEventListener("drop",e=>choose(e.dataTransfer.files[0]));
$("recognize").onclick=async()=>{ if(!file)return; const button=$("recognize"); button.disabled=true; button.innerHTML="Reading document…"; setStatus("Analyzing"); try { const body=new FormData(); body.append("file",file); const res=await fetch("/api/recognize",{method:"POST",body}); const data=await res.json(); if(!res.ok)throw Error(data.error); result=data; $("empty").hidden=true; $("editor").hidden=false; $("title").value=data.title; $("text").value=data.transcript; $("docType").textContent=data.document_type.toUpperCase(); $("lang").textContent=data.language; $("confidence").textContent=`${data.confidence}% confidence`; const review=$("review"); if(data.needs_review?.length){review.hidden=false;review.textContent="Review: "+data.needs_review.join(" · ")}else review.hidden=true; document.querySelectorAll(".exports button").forEach(x=>x.disabled=false); $("tableNote").textContent=data.table?"Table detected. CSV will preserve columns and rows.":"Document detected. TXT, DOCX and PDF preserve your edited transcription."; setStatus("Converted","done"); } catch(err){ setStatus("Needs setup"); alert(err.message); } finally { button.disabled=false;button.innerHTML="Convert handwriting <span>→</span>"; }};
document.querySelectorAll("[data-format]").forEach(button=>button.onclick=async()=>{const format=button.dataset.format;button.textContent="…";try{const payload={title:$("title").value,text:$("text").value,table:result?.table};const res=await fetch(`/api/export/${format}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!res.ok)throw Error("Export failed");const blob=await res.blob(),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="transcription."+format;a.click();URL.revokeObjectURL(a.href)}catch(e){alert(e.message)}finally{button.textContent=format.toUpperCase()}});
